export const Action = {
    FETCH_DATA : "FETCH_DATA",
    SORT_DATA : "SORT_DATA",
    FILTER_BY : "FILTER_BY",
    ADDTO_CART : "ADDTO_CART",
    REMOVE_CART : "REMOVE_CART",
    REMOVE_ALL : "REMOVE_ALL"
};